//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Priyanka_CustAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Priyanka_Customer
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string MobileNumber { get; set; }
        public string Status { get; set; }
        public List<string> ListCustomer { get; set; }
    }
}
